name: Check for broken links

on: [ push, pull_request ]

jobs:
  check-broken-links:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: BoundfoxStudios/action-hugo-link-check@v1
        with:
          hugo-root: .
          hugo-content-dir: ./content
          hugo-config: ./config.yaml